framework:
    secret: '%env(APP_SECRET)%'

    session:
        enabled: true
        storage_factory_id: session.storage.factory.native

    default_locale: 'ru'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - 'ru'

    csrf_protection: true

    validation:
        enable_attributes: true

    property_info:
        enabled: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
