_main:
    resource: '../src/Controller/'
    type: attribute
    prefix: /{_locale}
    defaults: { _locale: 'ru' }
    requirements:
        _locale: 'ru|en'

redirect_login:
    path: /login
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: app_login
        _locale: 'ru'
        permanent: true

redirect_logout:
    path: /logout
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: app_logout
        _locale: 'ru'
        permanent: true

redirect_admin:
    path: /admin
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: admin
        _locale: 'ru'
        permanent: true
